# Write your MySQL query statement below
SELECT 
    SU.USER_ID,
    ROUND(IFNULL(AVG(C.ACTION = 'CONFIRMED'),0),2)
     AS CONFIRMATION_RATE 

FROM SIGNUPS AS SU
LEFT JOIN CONFIRMATIONS C 
    ON SU.USER_ID = C.USER_ID
GROUP BY SU.USER_ID;